from tests.newmath import test_unittest

# Ejecutar los tests de vocales
test_unittest.test_deberia_contar_vocales_en_una_frase()
test_unittest.test_deberia_contar_vocales_en_una_palabra()
test_unittest.test_deberia_contar_vocales_en_una_frase_vacia()
test_unittest.test_deberia_contar_vocales_en_una_frase_con_numeros()
test_unittest.test_deberia_contar_vocales_en_una_frase_con_simbolos()
test_unittest.test_deberia_contar_vocales_en_una_frase_con_mayusculas()
test_unittest.test_deberia_contar_vocales_en_una_frase_con_minusculas()
test_unittest.test_deberia_contar_vocales_en_una_frase_con_espacios()
test_unittest.test_deberia_contar_vocales_en_una_frase_con_vocales_y_consonantes()

# Ejecutar los tests de multiplicar vocales
test_unittest.test_deberia_multiplicar_vocales_en_una_frase()
test_unittest.test_deberia_multiplicar_vocales_en_una_palabra()
test_unittest.test_deberia_multiplicar_vocales_en_una_frase_vacia()
test_unittest.test_deberia_multiplicar_vocales_en_una_frase_con_numeros()
test_unittest.test_deberia_multiplicar_vocales_en_una_frase_con_simbolos()
test_unittest.test_deberia_multiplicar_vocales_en_una_frase_con_mayusculas()
test_unittest.test_deberia_multiplicar_vocales_en_una_frase_con_minusculas()
test_unittest.test_deberia_multiplicar_vocales_en_una_frase_con_espacios()
test_unittest.test_deberia_multiplicar_vocales_en_una_frase_con_vocales_y_consonantes()
test_unittest.test_deberia_multiplicar_vocales_en_una_frase_con_vocales_repetidas()

# Ejecutar los tests de multiplicar factor
test_unittest.test_deberia_multiplicar_factor()
test_unittest.test_deberia_multiplicar_factor_de_cero()
test_unittest.test_deberia_multiplicar_factor_de_uno()
test_unittest.test_deberia_multiplicar_factor_de_dos()
test_unittest.test_deberia_multiplicar_factor_de_tres()
test_unittest.test_deberia_multiplicar_factor_de_cuatro()
test_unittest.test_deberia_multiplicar_factor_de_cinco()
test_unittest.test_deberia_multiplicar_factor_de_seis()
test_unittest.test_deberia_multiplicar_factor_de_siete()
test_unittest.test_deberia_multiplicar_factor_de_ocho()
test_unittest.test_deberia_multiplicar_factor_de_nueve()

# Ejecutar los tests de calcular factor fibonacci
test_unittest.test_deberia_calcular_factor_fibonacci_con_valores_por_defecto()
test_unittest.test_deberia_calcular_factor_fibonacci_con_valores_personalizados()
test_unittest.test_deberia_calcular_factor_fibonacci_con_valores_personalizados_dos()
test_unittest.test_deberia_calcular_factor_fibonacci_con_valores_personalizados_tres()
test_unittest.test_deberia_calcular_factor_fibonacci_con_valores_personalizados_cuatro()
test_unittest.test_deberia_calcular_factor_fibonacci_con_valores_personalizados_cinco()
test_unittest.test_deberia_calcular_factor_fibonacci_con_valores_personalizados_seis()
test_unittest.test_deberia_calcular_factor_fibonacci_con_valores_personalizados_siete()
test_unittest.test_deberia_calcular_factor_fibonacci_con_valores_personalizados_ocho()
test_unittest.test_deberia_calcular_factor_fibonacci_con_valores_personalizados_nueve()
